name: animated_list_item
description: A flutter package whitch provide Animation of items in ListView, GridView, SliverList, etc.
version: 0.0.1
repository: https://github.com/w830207/animated_list_item

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0